### ISSUE TITLE
Constantly disconnecting and reconnecting 

### ISSUE THREAD

**Issue by jerhms** [fourtf/chatterino#108]
The problem only occurs in reckful's chat. Happens nearly every 30 seconds. I tried to 'manually reload the chat.' 

Screenshot: https://imgur.com/Irp0aXz

**Comment by fourtf** [comment]
Yeah this has been happening to me recently, I'll look into it

jerhms <notifications@github.com> schrieb am So., 19. März 2017, 00:28:
