### ISSUE TITLE
Trojan:Win32/Fethar.B!cl

### ISSUE THREAD

**Issue by ZeZerT** [fourtf/chatterino#64]
Hello,

Windows Defender found a trojan in Chatterino, see attached screen. 
http://imgur.com/a/HAJls

> What it says (because i'm not sure you speak french) : 
> Category : Trojan 
> Description : Dangerous program blablabla
> Recommended action : delete
> Element : file:F:\Downloads\chatterino-win\Chatterino.exe

For reference, I downloaded the Windows version, date of 2016/09/24 14h05 from https://fourtf.com/chatterino/ of course. 
I downloaded it a second time 5mins ago, it gives me the same error. When still zipped, the Element given as trojan is : 

> file:C:\ProgramData\Microsoft\Windows Defender\LocalCopy\{19573E82-21A9-4811-80B0-A83393D08F22}-chatterino-win (1).zip
> file:C:\ProgramData\Microsoft\Windows Defender\Scans\FilesStash\6CCB6238-F1D5-1273-3CB6-A558220277E2_1d218dd591693ab

**Comment by fourtf** [comment]
I got the same error when I tried downloading it. I tweeted to microsoft, hope I'll get a message back!

**Comment by ZeZerT** [comment]
Thanks for the commitment !

**Comment by fourtf** [comment]
Microsoft updated their malware definitions and chatterino does not get flagged as a trojan anymore!
